# Cloud Foundry Java Buildpack
# Copyright 2013-2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
# Artifact resolution Configuration for the Mule container
# 
# Please replace <client_id> and <client_secret> with your Buildpack Nexus Proxy API credentials (supplied by MuleSoft)
# and <nexusUsername> and <nexusPassword> with your Mulesoft EE Nexus repository credentials (supplied by MuleSoft).
# Adjust version specification according to the runtime version to use (more information here:
# https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md#version-syntax-and-ordering).
#
# Alternatively, use your custom buildpack repository to host Mulesoft artifacts 
# (more information here: https://github.com/cloudfoundry/java-buildpack/blob/master/docs/extending-repositories.md)
# 
---
# 
# To use API Gateway Runtime, use the following configuration
#version: 2.+
#repository_root: "https://<client_id>:<client_secret>@pcf-buildpack-nexus-proxy.cloudhub.io/api/https/<nexusUsername>/<nexusPassword>/repository.mulesoft.org/443/releases-ee/com.mulesoft.anypoint/api-gateway-distribution-standalone"
#userjars_root: ""
#offlinepolicies_root: ""

#
# To use ESB Runtime, use the following configuration 
#version: 3.+
#repository_root: "https://<client_id>:<client_secret>@pcf-buildpack-nexus-proxy.cloudhub.io/api/https/<nexusUsername>/<nexusPassword>/repository.mulesoft.org/443/releases-ee/com.mulesoft.muleesb.distributions/mule-ee-distribution-standalone"
#userjars_root: ""
#offlinepolicies_root: ""

